[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Handle SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[context.production]
  command = "npm install && npm run build"

[context.production.environment]
  NODE_ENV = "production"
  VITE_SUPABASE_URL = "your-production-supabase-url"
  VITE_SUPABASE_ANON_KEY = "your-production-supabase-anon-key"

[context.deploy-preview.environment]
  NODE_ENV = "staging"
  VITE_SUPABASE_URL = "your-staging-supabase-url"
  VITE_SUPABASE_ANON_KEY = "your-staging-supabase-anon-key"
